ARG NODE_VERSION=18.18.2

FROM node:${NODE_VERSION}-slim as base

ARG PORT=80

ENV NODE_ENV=production

WORKDIR /src

# Build
FROM base as build

COPY --link package.json package-lock.json ./
RUN npm install --production=false

COPY --link . .

RUN npm run generate

# Run
FROM nginx:stable-alpine as final

COPY --from=build /src/dist /usr/share/nginx/html
EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]
